set village=84
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 0 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 1 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 2 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 3 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 4 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 7 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 8 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 10 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 11 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 12 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 14 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 15 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 16 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 18 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 19 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 20 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 21 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 22 0 2 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight.py 23 0 2 %village%
