set village=77
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 0 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 1 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 2 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 3 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 4 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 7 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 8 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 10 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 11 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 12 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 14 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 15 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 16 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 18 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 19 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 20 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 21 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 22 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwFight_bot.py 23 0 1 %village%