set village=3150
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 0 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 1 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 2 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 3 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 4 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 7 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 8 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 10 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 11 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 12 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 14 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 15 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 16 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 18 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 19 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 20 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 21 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 22 0 0 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 23 0 0 %village%
