set village=7870
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 0 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 1 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 2 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 3 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 4 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 7 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 8 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 10 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 11 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 12 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 14 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 15 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 16 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 18 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 19 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 20 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 21 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 22 0 1 %village%
d:\srv\python27\python.exe d:\srv\games\hero\gwHeal.py 23 0 1 %village%
